### ISSUE TITLE
Impa's House Cow uses Front exit of Impa's House for its hint region

### ISSUE THREAD

**Issue by r0bd0g** [OoTRandomizer/OoT-Randomizer#1047]
... rather than the back of the house as was intended.
I don't believe you can actually experience the consequences of this bug on the official builds, though.
This also means the "False" exit out of Impa's Cow region is doing nothing. Actually apparently it gets pruned as useless anyway?

**Comment by Roman971** [comment]
I can confirm this can't happen on this fork so it should probably be closed to avoid any confusion.

And yeah, the "False" exit does absolutely nothing, since hints are based on entrances, not exits. I remember mentioning that back when it was added or going to be added, but I guess it was kept anyway.
